[package]
name = "vs_image"
version = "0.2.0"
edition = "2021"

[dependencies]
image = "0.24"   # For image manipulation
rusttype = "0.9"  # For text rendering
imageproc = "0.23" # For image processing effects
rand = "0.8.5"
base64 = "0.22.1"
